apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
spec:
  monitoring:
    alertmanager:
      url: 'https://alertmanager.open-cluster-management-observability.svc:9095'
    thanosQuerier:
      url: 'https://rbac-query-proxy.open-cluster-management-observability.svc:8443'
  type: Monitoring

