# modified from https://github.com/rhobs/observability-operator/blob/a52ed9be7db4c346adbd54cfe4aa59d6324584fe/deploy/operator/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- observability-operator-deployment.yaml
# - observability-operator-service-account.yaml
# - observability-operator-cluster-role.yaml
# - observability-operator-cluster-role-binding.yaml
# - observability-operator-service.yaml

images:
- name: observability-operator
  newName: observability-operator
  newTag: 0.0.29
namespace: openshift-operators

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --openshift.enable
  target:
    group: apps
    kind: Deployment
    version: v1
